[package]
name = "warp-test"
version = "0.1.0"
authors = ["majorz"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
pretty_env_logger = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
